export let kanbanData: Object[] = [
    {
        id: 1,
        status: 'Open',
        description: 'Analyze the new requirements gathered from the customer.',
        type: 'Story',
        // Priority: 'Low',
        // Tags: 'Analyze,Customer',
        // Estimate: 3.5,
        title:'Demo Title',
        due_date:'10/14/2021',
        assignee: 'Nancy Davloio',
        rankId: 1,
        clinic_id:1,
        user_id:1,
        assignee_user:1,
        assignee_group:1,
        created_date:'09/14/2021',
    },
    {
        id: 2,
        status: 'Open',
        description: 'Analyze the new requirements gathered from the customer.',
        type: 'Story',
        // Priority: 'Low',
        // Tags: 'Analyze,Customer',
        // Estimate: 3.5,
        title:'Demo Title',
        due_date:'10/14/2021',
        assignee: 'Nancy Davloio',
        rankId: 1,
        clinic_id:1,
        user_id:1,
        assignee_user:1,
        assignee_group:1,
        created_date:'09/14/2021',
    },
    {
        id: 3,
        status: 'Done',
        description: 'Analyze the new requirements gathered from the customer.',
        type: 'Story',
        // Priority: 'Low',
        // Tags: 'Analyze,Customer',
        // Estimate: 3.5,
        title:'Demo Title',
        due_date:'10/14/2021',
        assignee: 'Nancy Davloio',
        rankId: 1,
        clinic_id:1,
        user_id:1,
        assignee_user:1,
        assignee_group:1,
        created_date:'09/14/2021',
    },
    
];